## for graphql-java-datetime https://github.com/donbeave/graphql-java-datetime

spring:
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false

graphql:
  # graphql-java-datetime
  datetime:
    scalars:
      localDate:
        format: yyyy/MM/dd
      localDateTime:
        #        format: yyyy-MM-dd'T'HH:mm:ss
        format: yyyy-MM-dd HH:mm:ss
      zone-conversion-enabled: false

